name: Unit Tests Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read
  actions: write

jobs:
  test:
    name: Run Unit Tests
    runs-on: macos-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
        
      - name: Install Dependencies
        working-directory: SwiftCoreUtilities
        run: swift package resolve
    
      - name: Install SwiftLint
        run: brew install swiftlint
    
      - name: List Available Schemes
        working-directory: SwiftCoreUtilities
        run: xcodebuild -list
    
      - name: List Available Simulators (Debugging)
        run: xcrun simctl list devices available
    
      - name: Boot iPhone Simulator (iPhone15, iOS 17.0)
        run: xcrun simctl boot CBEE3EE6-43C6-4096-AA39-9FD3719A3BFA
    
      - name: Reset Package Cache
        working-directory: SwiftCoreUtilities
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData
          rm -rf .build
          swift package reset
          swift package resolve

      - name: Run Unit Tests on iOS Simulator
        working-directory: SwiftCoreUtilities
        run: |
          xcodebuild test \
            -scheme SwiftCoreUtilities \
            -destination "platform=iOS Simulator,id=CBEE3EE6-43C6-4096-AA39-9FD3719A3BFA" \
            -skipPackagePluginValidation \
            -enableCodeCoverage YES | xcpretty
