name: Unit Tests Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Unit Tests
    runs-on: macos-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
        
      - name: Install Dependencies
        working-directory: SwiftCoreUtilities
        run: swift package resolve
      
      - name: Checkout Repository
        working-directory: SwiftCoreUtilities
        uses: sersoft-gmbh/xcodebuild-action@v3
        with:
          spm-package: './'
          scheme: SwiftCoreUtilities
          destination: platform=iOS
          action: test
