name: Unit Tests Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Unit Tests
    runs-on: macos-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Select Xcode Version
        run: sudo xcode-select -p
      
      - name: Set Working Directory to SwiftCoreUtilities
        run: cd SwiftCoreUtilities
        
      - name: Install Dependencies
        working-directory: SwiftCoreUtilities
        run: swift package resolve
        
      - name: List Available Simulators (Debugging)
        run: xcrun simctl list devices available
        
      - name: Boot iOS Simulator
        run: |
          UDID=$(xcrun simctl create "Custom iPhone" "iPhone 15" "iOS 17.0")
          xcrun simctl boot "$UDID"
          echo "Simulator Booted: $UDID"
          
      - name: Run Unit Tests on iPhone 15 (iOS 17.0)
        run: |
          xcodebuild test \
            -scheme SwiftCoreUtilities \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0' \
            -enableCodeCoverage YES | xcpretty
