name: Unit Tests Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read
  actions: write

jobs:
  test:
    name: Run Unit Tests
    runs-on: macos-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
        
      - name: Install Dependencies
        working-directory: SwiftCoreUtilities
        run: swift package resolve
      
      - uses: mxcl/xcodebuild@v3
        with:
          platform: iOS
          action: test
          code-coverage: true
          warnings-as-errors: false
